### PR TITLE
Add transparent background banner

### PR DESCRIPTION
**Pull request by shenxianpeng**
Trying to replace the current readme-banner which does not have a transparent background, so in the dark theme, it displays a white background.

### CODE REVIEW

**Comment by 2bndy5** [comment]
Did you want it to be the same dimensions? I can help.

**Comment by 2bndy5** [comment]
I think the README is actually doing some manipulation to the image:
https://github.com/cpp-linter/.github/blob/e9f8bbf7bbfbf3a49cef059e6c158ade2605b1de/profile/README.md?plain=1#L2

**Comment by shenxianpeng** [comment]
It's better? https://github.com/cpp-linter/.github/tree/update-banner/profile

**Comment by 2bndy5** [comment]
It does on desktop, but mobile is a little squished.

**Comment by shenxianpeng** [comment]
Yes, me too. I'll try to find a better width and height

**Comment by 2bndy5** [comment]
I think the max width used should be 320 (going off of common dimensions listed for portrait mode on various phones - see [this site](https://www.icwebdesign.co.uk/common-viewport-sizes))

**Comment by 2bndy5** [comment]
I think github supports the `min-width` and `min-height` style properties. So using the image dimensions 1163x320, the recommended minimum would be
```html
    <img src="/assets/readme-banner.png" min-width="320" min-height="88" alt="cpp-linter_brand_logo" />
```

**Comment by shenxianpeng** [comment]
In order to view the result in the local environment, I moved readme-banner.png to the profile folder and remove the assert folder.

I hope the image display is as big as possible, so I change to width to 400 and remove height from README.md, it looks display well now.

**Comment by 2bndy5** [comment]
Using [my above suggestion](https://github.com/cpp-linter/.github/pull/6#issuecomment-1225199056), `min-width` + `min-height` = constant aspect ratio but using as much space as possible.

Using a strict `width` limits the largest size the image will be. And without a `height` specified, the aspect ration may get distorted.

**Comment by shenxianpeng** [comment]
Updated with your suggestion, it looks great 👍

**Review by 2bndy5 — APPROVED** [review]
So pretty! 😍

**Comment by shenxianpeng** [comment]
Oh NO, it seems I can not remove the assets folder.

**Comment by 2bndy5** [comment]
> Oh NO, it seems I can not remove the assets folder.

I was just going to say, something didn't work 
image

**Comment by shenxianpeng** [comment]
It works now.

**Comment by shenxianpeng** [comment]
I think the current banner on the org overview page is a bit larger than I expected, and users may be drawn to the banner rather than the text/repositories below. 
@2bndy5 do you have any suggestions about how to make it smaller? it's okay to be 1/2 or 2/3 of what it is now.

**Comment by 2bndy5** [comment]
You could scale down the image. That's why it was so big to begin with. I needed something that could be scaled down because scaling an image up produced distortion.

**Pull request merged**
